# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('http_post_payload', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField()),
                ('test_vm', models.CharField(max_length=50)),
                ('test_spec', models.CharField(max_length=20)),
                ('total_iops', models.FloatField()),
                ('read_iops', models.FloatField()),
                ('write_iops', models.FloatField()),
                ('min_read_latency', models.FloatField()),
                ('max_read_latency', models.FloatField()),
                ('avg_read_latency', models.FloatField()),
                ('min_write_latency', models.FloatField()),
                ('max_write_latency', models.FloatField()),
                ('avg_write_latency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('http_headers', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_profile.Server'),
        ),
        migrations.AddField(
            model_name='profile',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_profile.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('report_time', 'test_vm', 'server')]),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('name', 'server')]),
        ),
    ]
