# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('http_post_payload', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('http_headers', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_profile.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('name', 'server')]),
        ),
    ]
