# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField()),
                ('test_vm', models.CharField(max_length=50)),
                ('test_spec', models.CharField(max_length=20)),
                ('total_iops', models.FloatField()),
                ('read_iops', models.FloatField()),
                ('write_iops', models.FloatField()),
                ('min_read_latency', models.FloatField()),
                ('max_read_latency', models.FloatField()),
                ('avg_read_latency', models.FloatField()),
                ('min_write_latency', models.FloatField()),
                ('max_write_latency', models.FloatField()),
                ('avg_write_latency', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='result',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_profile.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('report_time', 'test_vm')]),
        ),
    ]
