# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_profile', '0002_auto_20160119_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='http_post_payload',
            field=models.TextField(),
        ),
    ]
